import { test, expect } from '@playwright/test';

test('loogiin', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('shashankyadav@gmail.com');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('shashankyadav');
  await page.getByRole('button', { name: 'Log in' }).click();
  await expect(page.locator('div').nth(5)).toBeVisible();
});

test('book order', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Books' }).first().click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(1).click();
  await page.getByRole('link', { name: 'Shopping cart (1)' }).click();
  await page.getByLabel('Country:').selectOption('4');
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('shashankyadav@gmail.com');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('shashankyadav');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByLabel('Country:').selectOption('4');
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByLabel('Select a billing address from').selectOption('');
  await page.getByLabel('Country:').selectOption('4');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).fill('yhb');
  await page.getByRole('textbox', { name: 'Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Address 1:' }).fill('hj ');
  await page.getByRole('textbox', { name: 'Address 2:' }).click();
  await page.getByRole('textbox', { name: 'Address 2:' }).fill('jn ');
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('kn');
  await page.getByRole('textbox', { name: 'Phone number:' }).click();
  await page.getByRole('textbox', { name: 'Phone number:' }).fill('58745698');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('radio', { name: 'Cash On Delivery (COD) (7.00' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('cell', { name: 'You will pay by COD' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.order-review-data').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByRole('heading', { name: 'Thank you' })).toBeVisible();
  await page.getByText('Your order has been').click();
});

test('book jewellery', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Jewelry' }).first().click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(1).click();
  await page.getByRole('link', { name: 'Shopping cart (1)' }).click();
  await page.getByLabel('Country:').selectOption('93');
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('shashankyadav@gmail.com');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('shashankyadav');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByLabel('Country:').selectOption('93');
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByLabel('Select a billing address from').selectOption('');
  await page.getByLabel('Country:').selectOption('93');
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).fill('hgc');
  await page.getByRole('textbox', { name: 'Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Address 1:' }).fill('hgc');
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('874587458');
  await page.getByRole('textbox', { name: 'Phone number:' }).click();
  await page.getByRole('textbox', { name: 'Phone number:' }).fill('8745895874');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('radio', { name: 'Cash On Delivery (COD) (7.00' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.info').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.order-review-data').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByRole('heading', { name: 'Thank you' })).toBeVisible();
  await page.locator('.title').click();
  await expect(page).toHaveURL('https://demowebshop.tricentis.com/checkout/completed/');
});

test('book shirt and pant', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Apparel & Shoes' }).first().click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(4).click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(2).click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(3).click();
  await page.getByRole('link', { name: 'Shopping cart (2)' }).click();
  await page.getByLabel('Country:').selectOption('87');
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('shashankyadav@gmail.com');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('shashankyadav');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByLabel('Country:').selectOption('6');
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('radio', { name: 'Cash On Delivery (COD) (7.00' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('cell', { name: 'You will pay by COD' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.order-review-data').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByRole('heading', { name: 'Thank you' })).toBeVisible();
  await page.locator('.title').click();
  await expect(page).toHaveURL('https://demowebshop.tricentis.com/checkout/completed/');
});

